### ISSUE TITLE
for mtbf daily, create local gaia instance and fork gaiatest local repo

### ISSUE THREAD

**Issue by zapion** [Mozilla-TWQA/mtbf_operation#10]

**Comment by ypwalter** [comment]
Taking this.

**Comment by ypwalter** [comment]
created new task in mtbf-1
http://mtbf-1:8080/job/flame.master.daily.indep_gaia

Now, it can:
1. check out it's own local gaia instance and switch to the right branch
2. check out the exact commit that this build is in
